
import json
import unittest

import orjson

from model.datamodel.datamodel_root import DataModelRoot
from utils.tree_utils import compute_data_model_difference_map


class TreeUtilsTestCase(unittest.TestCase):

    def test_compute_data_model_difference_map(self):
        old_model_str = '{"id":"qLHx4QPjjw","name":"PanaTest-Minikube","data":{"type":"object","instanceOf":"PanaTest-Minikube:1.0.0","properties":{"S":{"type":"object","instanceOf":"PanaTest-Minikube.S:1.0.0","properties":{"A1":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}},"A2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2:1.0.0","properties":{"WCell3":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell3:1.0.0","properties":{"Modbus":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell3.Modbus:1.0.0","properties":{"IntegratedSin":{"version":"1.0.0","type":"double"}}}}},"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}}}},"S2":{"type":"object","instanceOf":"PanaTest-Minikube.S2:1.0.0","properties":{"A1":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}},"A2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}}}}},"label":"","unit":"","description":"","UUID":"eq04j35u5v0p9uiy","tags":[]},"deleted":false,"version":"1.0.0"}'
        new_model_str = '{"id":null,"name":"PanaTest-Minikube","data":{"type":"object","instanceOf":"PanaTest-Minikube:1.0.0","properties":{"S":{"type":"object","instanceOf":"PanaTest-Minikube.S:1.0.0","properties":{"A1":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S.A1.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegerValue":{"version":"1.0.0","type":"integer"},"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}},"A2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2:1.0.0","properties":{"WCell3":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell3:1.0.0","properties":{"Modbus":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell3.Modbus:1.0.0","properties":{"IntegerValue":{"version":"1.0.0","type":"integer"},"IntegratedSin":{"version":"1.0.0","type":"double"}}}}},"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S.A2.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegerValue":{"version":"1.0.0","type":"integer"},"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}}}},"S2":{"type":"object","instanceOf":"PanaTest-Minikube.S2:1.0.0","properties":{"A1":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A1.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegerValue":{"version":"1.0.0","type":"integer"},"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}},"A2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2:1.0.0","properties":{"PLine2":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2:1.0.0","properties":{"WCell4":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2.WCell4:1.0.0","properties":{"DriverMachine":{"type":"object","instanceOf":"PanaTest-Minikube.S2.A2.PLine2.WCell4.DriverMachine:1.0.0","properties":{"IntegerValue":{"version":"1.0.0","type":"integer"},"IntegratedSin":{"version":"1.0.0","type":"double"}}}}}}}}}}}},"label":"","unit":"","description":"","UUID":null,"tags":[]},"deleted":null,"version":"1.0.0"}'

        old_model = DataModelRoot.from_dict(orjson.loads(old_model_str))
        new_model = DataModelRoot.from_dict(orjson.loads(new_model_str))

        diff_dict = compute_data_model_difference_map(old_model, new_model)
        print(diff_dict)

        self.assertTrue(True)